version: "3.9"

name: email-consumer-service
services:
  db:
    image: postgres:16.2-alpine3.19
    ports:
      - "${DB_SERVER_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-dev}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-strongpassword}
      POSTGRES_DB: ${DB_DATABASE:-email_queue_consumer}
    volumes:
      - email_queue_consumer-service-postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13.1-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME-changeme}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD-strongpassword}
    ports:
      - "${RABBITMQ_PORT-5672}:5672"
      - 15672:15672
    volumes:
      - email_queue_consumer-rabbitmq_data:/var/lib/rabbitmq

  consumer-1:
    container_name: email-consumer-service-consumer-1
    build:
      context: .
      dockerfile: docker/consumer/Dockerfile
    image: email_queue_consumer:latest

  consumer-2:
    container_name: email-consumer-service-consumer-2
    build:
      context: .
      dockerfile: docker/consumer/Dockerfile
    image: email_queue_consumer:latest

volumes:
  email_queue_consumer-service-postgres-data:
  email_queue_consumer-service-redis-data:
  email_queue_consumer-rabbitmq_data:
